from enum import Enum

from pydantic import BaseModel, Field


class TicketCategory(str, Enum):
    """Supported customer-support ticket categories."""

    BILLING = "Billing"
    LOGIN_ISSUE = "Login Issue"
    TECHNICAL_ISSUE = "Technical Issue"
    REFUND = "Refund"
    COMPLAINT = "Complaint"
    GENERAL_INQUIRY = "General Inquiry"


class TicketPriority(str, Enum):
    """Supported ticket priority levels."""

    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class CustomerSentiment(str, Enum):
    """Supported customer sentiment categories."""

    CALM = "Calm"
    CONFUSED = "Confused"
    FRUSTRATED = "Frustrated"
    ANGRY = "Angry"


class TicketClassification(BaseModel):
    """Structured classification generated by the LLM."""

    category: TicketCategory = Field(
        description="Primary category of the support ticket.",
    )

    priority: TicketPriority = Field(
        description="Priority assigned to the support ticket.",
    )

    sentiment: CustomerSentiment = Field(
        description="Customer sentiment expressed in the message.",
    )


class EscalationDecision(BaseModel):
    """Structured escalation decision generated by the LLM."""

    escalation_needed: bool = Field(
        description="Whether human escalation is required.",
    )

    reason: str = Field(
        description="Short explanation for the escalation decision.",
    )