from textwrap import dedent


def build_classification_prompt(
    customer_message: str,
) -> str:
    """
    Build the customer-ticket classification prompt.

    Args:
        customer_message: Customer support message.

    Returns:
        Classification prompt.
    """
    return dedent(
        f"""
        Classify the following customer support message.

        Customer Message:
        {customer_message}

        Category must be exactly one of:

        - Billing
        - Login Issue
        - Technical Issue
        - Refund
        - Complaint
        - General Inquiry

        Priority must be exactly one of:

        - Low
        - Medium
        - High
        - Critical

        Sentiment must be exactly one of:

        - Calm
        - Confused
        - Frustrated
        - Angry

        Classification guidance:

        Billing:
        Payment, invoice, charge, subscription billing, or transaction issues.

        Login Issue:
        Password, login, authentication, locked account, or account-access issues.

        Technical Issue:
        Bugs, errors, broken functionality, crashes, or system problems.

        Refund:
        Requests for money back or questions about refund eligibility.

        Complaint:
        Explicit dissatisfaction or complaints about a product or service.

        General Inquiry:
        Questions that do not clearly belong to another category.

        Priority guidance:

        Low:
        General questions or low-impact issues.

        Medium:
        Customer inconvenience without serious impact.

        High:
        Significant financial, access, technical, or customer-impacting issue.

        Critical:
        Severe outage, major business impact, or highly urgent issue.

        Sentiment:
        Infer sentiment only from the customer's actual message.

        Return ONLY valid JSON using this exact structure:

        {{
            "category": "Billing",
            "priority": "High",
            "sentiment": "Frustrated"
        }}

        Rules:
        - Return JSON only.
        - Do not include markdown.
        - Do not add extra fields.
        - Do not invent facts.
        """
    ).strip()


def build_response_prompt(
    customer_message: str,
    category: str,
    priority: str,
    policy_guidance: str,
) -> str:
    """
    Build the customer-response generation prompt.

    Args:
        customer_message: Original customer message.
        category: Classified ticket category.
        priority: Classified ticket priority.
        policy_guidance: Deterministic policy information.

    Returns:
        Response-generation prompt.
    """
    return dedent(
        f"""
        Write a professional customer support response.

        Customer Message:
        {customer_message}

        Ticket Category:
        {category}

        Ticket Priority:
        {priority}

        Company Policy Guidance:
        {policy_guidance}

        Requirements:
        - Be polite and empathetic.
        - Address the customer's actual concern.
        - Follow the provided company policy.
        - Do not promise actions that policy does not allow.
        - Do not claim an action has already been completed.
        - Ask for missing information when necessary.
        - Keep the response clear and practical.
        - Do not mention internal classification or escalation logic.
        """
    ).strip()


def build_escalation_prompt(
    customer_message: str,
    category: str,
    priority: str,
    sentiment: str,
    policy_guidance: str,
    draft_response: str,
) -> str:
    """
    Build the escalation-decision prompt.

    Args:
        customer_message: Original customer message.
        category: Ticket category.
        priority: Ticket priority.
        sentiment: Customer sentiment.
        policy_guidance: Relevant support policy.
        draft_response: Draft response generated by the LLM.

    Returns:
        Escalation-analysis prompt.
    """
    return dedent(
        f"""
        Determine whether this customer-support ticket requires
        human escalation.

        Customer Message:
        {customer_message}

        Category:
        {category}

        Priority:
        {priority}

        Sentiment:
        {sentiment}

        Policy Guidance:
        {policy_guidance}

        Draft Response:
        {draft_response}

        Escalate when one or more of the following applies:

        - Priority is High or Critical.
        - Customer sentiment is Angry.
        - There is an incorrect, duplicate, or disputed charge.
        - Refund eligibility is unclear or outside the available policy.
        - A technical issue is blocking important business activity.
        - The issue involves legal, compliance, or other sensitive concerns.
        - The available policy does not safely resolve the issue.

        Do not escalate a normal low-risk request without a reason.

        Return ONLY valid JSON:

        {{
            "escalation_needed": true,
            "reason": "Short explanation"
        }}

        Rules:
        - Return JSON only.
        - Do not include markdown.
        - Do not add extra fields.
        - Base the decision only on the supplied information.
        """
    ).strip()