def build_planning_prompt(user_goal: str) -> str:
    """
    Build the prompt for the planning stage.

    Args:
        user_goal: Goal provided by the user.

    Returns:
        Planning prompt.
    """
    return f"""
You are an expert AI planner.

Create a practical step-by-step execution plan for the following goal.

Goal:
{user_goal}

Requirements:
- Break the goal into logical steps.
- Keep each step practical and actionable.
- Order the steps correctly.
- Briefly explain the purpose of each step.
- Avoid unnecessary details.
- Use numbered steps.
""".strip()


def build_execution_prompt(
    user_goal: str,
    plan_output: str,
) -> str:
    """
    Build the prompt for the execution stage.

    Args:
        user_goal: Original user goal.
        plan_output: Plan generated by the planning stage.

    Returns:
        Execution prompt.
    """
    return f"""
You are an expert AI execution assistant.

Goal:
{user_goal}

Execution Plan:
{plan_output}

Execute the plan and produce the best possible result.

Requirements:
- Follow the plan carefully.
- Preserve the original goal.
- Complete each relevant step.
- Provide practical and useful details.
- Use clear, structured formatting.
- Do not discuss the planning process unnecessarily.
""".strip()


def build_refinement_prompt(
    user_goal: str,
    execution_output: str,
) -> str:
    """
    Build the prompt for the refinement stage.

    Args:
        user_goal: Original user goal.
        execution_output: Output produced during execution.

    Returns:
        Refinement prompt.
    """
    return f"""
You are an expert AI reviewer and editor.

Goal:
{user_goal}

Current Output:
{execution_output}

Review the output critically and produce an improved final version.

Requirements:
- Preserve correct information.
- Improve clarity.
- Improve organization and structure.
- Improve completeness.
- Fix weak or unclear sections.
- Remove unnecessary repetition.
- Make the final answer practical and professional.
- Return only the improved final result.
""".strip()