from typing import Literal

from openai import OpenAI

from app.config import (
    get_deepseek_api_key,
    get_deepseek_base_url,
    get_deepseek_model,
    get_openai_api_key,
    get_openai_model,
)

ModelProvider = Literal["openai", "deepseek"]


def get_client_and_model(provider: ModelProvider):
    """
    Create an LLM client and return its model configuration.

    Args:
        provider: LLM provider to use.

    Returns:
        Tuple containing:
            - OpenAI-compatible client
            - Model name

    Raises:
        ValueError: If the provider is unsupported.
    """
    provider = provider.lower().strip()

    if provider == "openai":
        client = OpenAI(
            api_key=get_openai_api_key(),
        )

        return client, get_openai_model()

    if provider == "deepseek":
        client = OpenAI(
            api_key=get_deepseek_api_key(),
            base_url=get_deepseek_base_url(),
        )

        return client, get_deepseek_model()

    raise ValueError(
        f"Unsupported model provider: {provider!r}. "
        "Expected 'openai' or 'deepseek'."
    )


def call_llm(
    prompt: str,
    provider: ModelProvider,
) -> str:
    """
    Send a prompt to the selected LLM provider.

    Args:
        prompt: User prompt sent to the model.
        provider: LLM provider to use.

    Returns:
        Text generated by the model.
    """
    client, model = get_client_and_model(provider)

    print(f"Using provider: {provider}")
    print(f"Using model: {model}")

    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": "You are a helpful AI research assistant.",
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
    )

    if response.usage:
        print("\n=== Token Usage ===")
        print("Prompt tokens:", response.usage.prompt_tokens)
        print("Completion tokens:", response.usage.completion_tokens)
        print("Total tokens:", response.usage.total_tokens)

    return response.choices[0].message.content or ""