from typing import Final

import gradio as gr
from agents import Agent, Runner, set_default_openai_key
from app.config import (
    get_openai_api_key,
    get_openai_model,
)
from app.prompts import get_research_agent_instructions
from app.tools import web_search

AGENT_NAME: Final = "Research Copilot"

SYSTEM_INPUT_TEMPLATE: Final = """
Research the following topic and produce a clear, well-supported report.

Research Topic:
{topic}
""".strip()


# Configure the OpenAI Agents SDK.
set_default_openai_key(
    get_openai_api_key(),
)


def create_research_agent() -> Agent:
    """
    Create and configure the Research Copilot agent.

    Returns:
        Configured research agent.
    """
    return Agent(
        name=AGENT_NAME,
        model=get_openai_model(),
        instructions=get_research_agent_instructions(),
        tools=[
            web_search,
        ],
    )


research_agent = create_research_agent()


async def run_research_copilot(
    topic: str,
) -> str:
    """
    Run the Research Copilot agent.

    Args:
        topic: Research topic provided by the user.

    Returns:
        Final research report generated by the agent.
    """
    topic = topic.strip()

    if not topic:
        return "Please enter a research topic."

    try:
        user_input = SYSTEM_INPUT_TEMPLATE.format(
            topic=topic,
        )

        result = await Runner.run(
            starting_agent=research_agent,
            input=user_input,
        )

        return result.final_output

    except Exception as exc:  # noqa: BLE001
        return f"**Research Agent Error:** {exc}"


with gr.Blocks() as demo:
    gr.Markdown(
        "# Research Copilot — OpenAI Agents SDK"
    )

    gr.Markdown(
        "Enter a research topic. The agent can search the web, "
        "analyze the results, and produce a structured research report."
    )

    topic_input = gr.Textbox(
        label="Research Topic",
        placeholder=(
            "Example: Future of AI agents in enterprise automation"
        ),
        lines=4,
    )

    run_button = gr.Button(
        "Run Research Copilot",
        variant="primary",
    )

    output = gr.Markdown(
        label="Research Report",
    )

    run_button.click(
        fn=run_research_copilot,
        inputs=topic_input,
        outputs=output,
    )


if __name__ == "__main__":
    demo.launch()